### ISSUE TITLE
 Can't verify signatures for the downloads

### ISSUE THREAD

**Issue by sionleroux** [schibsted/strongbox#43]
##### ISSUE TYPE
 - Documentation Report

##### COMPONENT NAME
pre-installation

##### SUMMARY

I tried to verify the downloaded file from [here](https://dl.bintray.com/strongbox/strongbox-generic/) but the public key mentioned in [the Wiki](https://github.com/schibsted/strongbox/wiki/Install-the-CLI) seems not to match and I couldn't find it on the usual public key servers.

##### STEPS TO REPRODUCE
Download the binary and the matching key. Try to verify the file but the key isn't found and doesn't seem to match the one provided in the documentation.

```bash
gpg --import strongbox.pgp
wget https://dl.bintray.com/strongbox/strongbox-generic/:strongbox-cli-0.2.7.tar.gz
wget https://dl.bintray.com/strongbox/strongbox-generic/:strongbox-cli-0.2.7.tar.gz.asc
gpg strongbox-cli-0.2.7.tar.gz.asc
```

In the above, `strongbox.pgp` is this content:

```
-----BEGIN PGP PUBLIC KEY BLOCK-----

mQENBFnA4+ABCADQJwX+1TOdwLt3Aw4kk9BwAzdYVoeZXOU1sb/wxQ+a0VcG9JPj
gBaqdxv0xfPNChFaeyYV1lkv61R9PKO0tDfwoijQRQS1+IhhJKi6nwYvLVKOQ2RS
7wOjj/T06gYvOYHALdyEYqnvzt/8hewNv7+yQbmgel8wUiOVQY3zdZ85HGY3ui9z
p6pS10fQWqrba8aSa1Px31D2hxzRpNEH5t2dh87uQ88XDFyGvBRoGvk+ZcqNtjBT
Eyn0bVeoxxX7NGjvOBcOXdlYLMtxVypT9Q+RBDwcY2clWj18KDoe5n1pSTzt1OVd
wEs0cqtLvaC5iNwnZ41L4a3SsWLPOBPNgJkJABEBAAG0L1N0cm9uZ2JveCBTaWdu
aW5nIEtleSA8c3Ryb25nYm94QHNjaGlic3RlZC5jb20+iQE3BBMBCgAhBQJZwOPg
AhsDBQsJCAcDBRUKCQgLBRYCAwEAAh4BAheAAAoJEBl0S+d+lmCsAQgH/112flrb
ypyYoEMfclFmTPfP7oZGTRb9zWHOdgnVvJcTJtqUqhjvBUD17YbHOQYF/jaqRdvf
uOIlH6+srd0Ku9GWRqnkOlg5zaWtnM/MGaSOR1sOunVLbiM5fD3+JikGpui3BAUb
pwEDpzLjCI0pTEukashG7Pyk0qTyc1vzsTazaCm02XDXRfmoWAUEI4rQzWYjubr1
J6WWNnIB4n1TzPhqSMmFYP2yfp6jejUKT62KHEizQiPO4VAqj6yoXubQttwVd9MS
YnvPyxvpO4WMvZy0XkI56f6S8nXjhuJ40hHe4HUJ5qJJFEOZ0fP9uGQCvzAVxMIh
/V8nNRCAjiArdzi5AQ0EWcDj4AEIAMeLWII/hMHxkbGn+z+WZbzUhLQwjTIuHC9u
eH/e/12pYQTFtWI5mzWV09f8oRSdyA7cFQfpPOjlBZ9WEG97dAMxl5azuEfTH43l
FknrVjXZDDDjiiWE9Ce3cKeS63CEtKpXUU11+1tNrTji6VbGmaGbEVo6BF3i17QE
Z5e1FOqYes0kNjJIEJ/GBhUq491LXnjDT32/DLDvs1NVraunSCdagevRZyWj17yo
wsQ0gmRU97bNx4lnTWHoVrgQTa03L2gzTxw9TKDqkW2aG0UL9mPY7yu8kvoNe0AY
PZ/ei78vXSW0MEtmYUEJxC8fkxMpwSG2WVer8p2soud3KkTynmEAEQEAAYkBHwQY
AQoACQUCWcDj4AIbDAAKCRAZdEvnfpZgrIpOB/47aeLKgBGjUu73wWHikjRXdIVq
YY+DqKfEu6DOKSY5mKwAQFc6EqhX5/dBWZvSDFC9PJ1Qry+BC5IeK+43DjAeO6Xw
Yej2wsTKbbSPYHNcVLdbGwwtjdOdtkkJhkeJNAEXZ0ZnEOQO5uuwHDMMC1oVsyDH
V+9tLEyVwgn7Fvv2I7VftGDhtwtxnmepgsCbPgVlN4rh7fCJ66KTPhbsmsbRcFbB
yTfMQ9zciWYMMekbGMTpT76Od8kHu4xn+O3a9CGJ1Nh39kHqfiU1piyOszYOdgQn
6DvyD9ArPKKivN35J6+78y8QpjJyjrNVOGTp91jpBMpKH8o5UMa3eqJtJd+O
=s/3Z
-----END PGP PUBLIC KEY BLOCK-----
```
from [the Wiki](https://github.com/schibsted/strongbox/wiki/Install-the-CLI#manual-configuration). It is shown in gpg tool as:

```
pub   rsa2048 2017-09-19 [SC]
      3C35E931BC569D90310676BB19744BE77E9660AC
uid           [ unknown] Strongbox Signing Key <strongbox@schibsted.com>
sub   rsa2048 2017-09-19 [E]
```

##### EXPECTED RESULTS
Verified file. Or at least that you can import `4EBC11A759502FAE` from a public key server and then verify it, e.g. `gpg --recv-keys 4EBC11A759502FAE`.

##### ACTUAL RESULTS
```
gpg: WARNING: no command supplied.  Trying to guess what you mean ...
gpg: assuming signed data in 'strongbox-cli-0.2.7.tar.gz'
gpg: Signature made Fri 24 Nov 2017 16:42:23 CET
gpg:                using RSA key 4EBC11A759502FAE
gpg: Can't check signature: No public key
```

Either I am making some really newbie mistake with the GPG tool or `4EBC11A759502FAE` and `3C35E931BC569D90310676BB19744BE77E9660AC` are _really_ not the same key and I got the wrong key from the Wiki?

**Comment by stiankri** [comment]
Thank you for you interest in Strongbox, and apologies for the inconvenience.

Unfortunately we are currently using a different key for the tarballs than for the RPMs and Debs. The RPMs and Debs are signed on Travis before they are uploaded to Bintray -- with a key that is only accessible to Travis. We have not gotten around to sign the tarball on Travis, and opted to just let Bintray sign those for us. Bintray uses a different key which is mentioned in the [Deb installation guide](https://github.com/schibsted/strongbox/wiki/Install-the-CLI#deb-linux-distributions-ubuntudebian---manual): https://bintray.com/user/downloadSubjectPublicKey?username=strongbox. I agree that both the correct approach and intuitive behavior would be to sign the tarball on Travis, using the key you tried to use.

The explanation for why we have two keys (which is not related to the tarballs) is that Debian by default checks the signature of the repository metadata rather than the Deb itself. Given that Bintray manages the repository metadata for us, it also needs to sign the metadata. We were not aware of this before setting things up, and had thought that we could do everything with one key on Travis. While Debian only verifies the repository metadata, it is still possible to verify the Deb with the signature from Travis, but this has not been documented. Changing the model to trust Bintray completely would simplify things, but
 I don't think we'll do that. 

**Suggested action items**
 - Improve documentation for how signing is done and should be verified
 - Sign the tarball using the Strongbox signing key on Travis before uploading to Bintray
 - Look into if the Bintray GPG key can be a subkey of the one in Travis to avoid having two separate keys

**Comment by xen0l** [comment]
IMO, the most straightforward option here would be to disable signing tarballs by Bintray and use Travis to sign the tarball. Once signed, we will upload both the tarball and signed file to Bintray.

**Comment by stiankri** [comment]
@xen0l Agreed. The two other action items was related to cleaning up signing in general.
